security:
    enable_authenticator_manager: true
    providers:
        in_memory: { memory: null }
    firewalls:
        api:
            pattern: ^/api/
            security: false  # Disable security for the API endpoints or configure your own
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            # If you want to enable authentication, add the necessary configuration here
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
