# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  NoteReact\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
      - "../src/xdebug_stub.php"

  # inject default LoggerInterface
  # Ensures `logger` is injected correctly if not otherwise configured
  logger:
    alias: "monolog.logger" # Use the default logger service provided by Symfony Monolog

  # register NoteFactory
  NoteReact\Factory\NoteFactory:
    arguments:
      $logger: "@logger" # inject default LoggerInterface
      $menuService: '@NoteReact\Service\MenuService'

  NoteReact\Service\:
    resource: "../src/Service"
    autowire: true
    autoconfigure: true


  NoteReact\Repository\:
    resource: "../src/Repository"
    calls:
      - method: "setLogger"
        arguments:
          - "@logger"
    autowire: true
    autoconfigure: true


  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
